In [101]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')

In [102]:
df = sns.load_dataset('iris')

In [103]:
df.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [104]:
df['species'].unique()

array(['setosa', 'versicolor', 'virginica'], dtype=object)

In [105]:
from sklearn.model_selection import train_test_split

In [108]:
X = df.drop('species', axis=1)
Y = df['species']

In [109]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=42)

In [110]:
from sklearn.neighbors import KNeighborsClassifier

In [127]:
model_knn = KNeighborsClassifier(n_neighbors=13)

In [128]:
model_knn.fit(X_train, Y_train)

KNeighborsClassifier(n_neighbors=13)

In [129]:
model_knn.score(X_test, Y_test)

1.0

In [130]:
from sklearn.svm import SVC

In [139]:
model_svm = SVC(gamma='auto')

In [140]:
model_svm.fit(X_train, Y_train)

SVC(gamma='auto')

In [141]:
model_svm.score(X_test, Y_test)

1.0

In [142]:
# now let's use Grid Search CV

In [143]:
from sklearn.model_selection import GridSearchCV

In [145]:
classifier = GridSearchCV(model_svm,param_grid={'C':[1,10,20,30,50,100,500],'kernel':['rbf','linear']},cv=5,return_train_score=False)

In [146]:
classifier.fit(X, Y)

GridSearchCV(cv=5, estimator=SVC(gamma='auto'),
             param_grid={'C': [1, 10, 20, 30, 50, 100, 500],
                         'kernel': ['rbf', 'linear']})

In [148]:
results = pd.DataFrame(classifier.cv_results_)

In [150]:
results[['param_C','param_kernel','mean_test_score']]

    param_C param_kernel  mean_test_score
0         1          rbf         0.980000
1         1       linear         0.980000
2        10          rbf         0.980000
3        10       linear         0.973333
4        20          rbf         0.966667
5        20       linear         0.966667
6        30          rbf         0.960000
7        30       linear         0.960000
8        50          rbf         0.960000
9        50       linear         0.966667
10      100          rbf         0.960000
11      100       linear         0.966667
12      500          rbf         0.953333
13      500       linear         0.966667